
first_file=input("Enter the name of the first file")
second_file=input("Enter the name of the second file")
f1=open("1.txt" , "r")
f2=open(second_file , "r")
print(f"Content of first file before appending : \n {f1.read()}" )
print(f"Content of second file before appending : \n {f2.read()}")
f1.close()
f2.close()
f1=open(first_file , "a")
f2=open(second_file , "r")
f1.write(f2.read())
f1.seek(0)
f2.seek(0)
print(f"Content of both files after appending: \n {f1.read()}")
print(f"Content of both files after appending : \n {f2.read()}")
f1.close()
f2.close()